# Generated by Django 2.0 on 2017-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pos_in_list',
            field=models.IntegerField(default=0),
        ),
    ]
